options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include:

      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed

      For series=Precise we support cloud archives for openstack-release:
         * icehouse

      For series=Trusty we support cloud archives for openstack-release:
         * juno
         * kilo
         * ...

      NOTE: updating this setting to a source that is known to provide
      a later version of OpenStack will trigger a software upgrade.
  database-user:
    default: heat
    type: string
    description: Username for database access
  database:
    default: heat
    type: string
    description: Database name
  instance-user:
    default:
    type: string
    description: |
      The default user for new instances. This option is deprecated as of Juno.
      If left empty, Heat will use the default user set up with your cloud
      image (for OS::Nova::Server) or 'ec2-user' (for AWS::EC2::Instance).
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  rabbit-user:
    default: heat
    type: string
    description: Username to request access on rabbitmq-server.
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ virtual host to request access on rabbitmq-server.
  encryption-key:
    default: ""
    type: string
    description: Encryption key used for authentication info in database
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  # Per-service HTTPS configuration.
  ssl_cert:
    type: string
    default:
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Heat's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    default:
    description: SSL key to use with certificate specified as ssl_cert.
  ssl_ca:
    type: string
    default:
    description: |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
  os-public-hostname:
    type: string
    default:
    description: |
      The hostname or address of the public endpoints created for heat
      in the keystone identity provider.
      .
      This value will be used for public endpoints. For example, an
      os-public-hostname set to 'heat.example.com' with ssl enabled will
      create the following public endpoints for ceilometer:
      .
      https://ceilometer.example.com:8777/
